name: swarm
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - brotli==1.2.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - datasets==2.15.0
      - dill==0.3.7
      - distro==1.9.0
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.3
      - filetype==1.2.0
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - func-timeout==4.3.5
      - google-ai-generativelanguage==0.10.0
      - google-api-core==2.29.0
      - google-auth==2.47.0
      - googleapis-common-protos==1.72.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.2
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==1.0.1
      - langchain-core==1.0.0
      - langchain-google-genai==3.0.0
      - langchain-openai==1.0.0
      - langgraph==1.0.6
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.6
      - langgraph-sdk==0.3.3
      - langsmith==0.6.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - multidict==6.7.0
      - multiprocess==0.70.15
      - numpy==1.26.4
      - openai==2.6.0
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.4
      - pyarrow==22.0.0
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.14
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - ruff==0.14.11
      - safehttpx==0.1.7
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - tenacity==9.1.2
      - tiktoken==0.7.0
      - tomlkit==0.13.3
      - tqdm==4.66.5
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uuid-utils==0.13.0
      - uvicorn==0.40.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /opt/anaconda3/envs/swarm
